uvc-frame-parser: Stream::codec is dropped since ffmpeg_5_0
error[E0599]: no method named `codec` found for struct `StreamMut<'_>` in the current scope
   --> utils/uvc-frame-parser/src/lib.rs:212:49
    |
212 |                 let mut encoder = output_stream.codec().encoder().video()?;
    |                                                 ^^^^^ method not found in `StreamMut<'_>`