fix usb-keyboard and ffmpeg .codec; set up CI to build all crates (#46)
* fix(hid): no-std suppport

* keyboard-types supports no-std since 0.8, so update it and solves the breakage
* String and Vec requires alloc crate in no-std

* fix(hid): the keyboard example requires libusb feature

* ci: build usb-keyboard and the example

* ci: cargo build --workspace

* uvc-frame-parser: Stream::codec is dropped since ffmpeg_5_0

error[E0599]: no method named `codec` found for struct `StreamMut<'_>` in the current scope
   --> utils/uvc-frame-parser/src/lib.rs:212:49
    |
212 |                 let mut encoder = output_stream.codec().encoder().video()?;
    |                                                 ^^^^^ method not found in `StreamMut<'_>`